### ISSUE TITLE
research on custom kubernetes controller

### ISSUE THREAD

**Issue by smhmayboudi** [smhmayboudi/custom-kubernetes-controller#1]
Familiarize myself with the Concepts and Tools

**Comment by smhmayboudi** [comment]
# references

1. https://kubernetes.io/docs/concepts/overview/working-with-objects/
2. https://kubernetes.io/docs/concepts/architecture/controller/
3. https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
4. https://sdk.operatorframework.io/docs/installation/
5. https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/

**Comment by smhmayboudi** [comment]
# Objects In Kubernetes

## Kubernetes Object Management

```shell
kubectl create deployment nginx --image nginx
kubectl create -f nginx.yaml # create a object
kubectl delete -f nginx.yaml -f redis.yaml # delete a object
kubectl replace -f nginx.yaml # update a object
kubectl diff -f configs/ && kubectl apply -f configs/ # make a patch & apply it
```

## Object Names and IDs

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo # RFC1123 & RFC1035(start with char), len(name) <= 63
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```
